# Generated by Django 3.0.3 on 2020-02-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('phone', models.CharField(default='', max_length=11)),
            ],
        ),
    ]
